<?php

/**
 * @file
 * Add Topbar Message to the page.
 */

/**
 * Implements hook_permission().
 */
function topbar_msg_permission() {
  return array(
    'administer topbar_msg' => array(
      'title' => t('Administer Topbar Message'),
      'description' => t('Allows users to administer Topbar Message settings.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function topbar_msg_menu() {
  $items = array();

  $items['admin/config/system/topbar-message'] = array(
    'title' => t('Topbar Message'),
    'description' => t('Configure Topbar Message settings.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('topbar_msg_settings_form'),
    'access arguments' => array('administer topbar_msg'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'topbar_msg.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_help().
 */
function topbar_msg_help($path, $arg) {
  switch ($path) {
    case 'admin/help#topbar_msg':
      return t('<p>The Topbar Message module allows the administrator to add a configurable Topbar Message to the page. Display can be set either as site wide or controlled via the context module.</p>');
  }
}

/**
 * Implements hook_ctools_plugin_api().
 */
function topbar_msg_ctools_plugin_api($module, $api) {
  if ($module == 'context' && $api == 'plugins') {
    return array('version' => 3);
  }
}

/**
 * Implements hook_context_registry().
 */
function topbar_msg_context_registry() {
  return array(
    'reactions' => array(
      'topbar_msg_add' => array(
        'title' => t('Topbar Message'),
        'plugin' => 'topbar_msg_context_reaction_add',
        'description' => t('Add Topbar Message to the page.'),
      ),
    ),
  );
}

/**
 * Implements hook_context_plugins().
 */
function topbar_msg_context_plugins() {
  $plugins = array();

  $plugins['topbar_msg_context_reaction_add'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'topbar_msg') . '/plugins',
      'file' => 'topbar_msg_context_reaction_add.inc',
      'class' => 'topbar_msg_context_reaction_add',
      'parent' => 'context_reaction',
    ),
  );

  return $plugins;
}

/**
 * Implements hook_page_alter().
 */
function topbar_msg_page_alter(&$page) {
  if (variable_get('topbar_msg_enable', 0)) {
    $display = variable_get('topbar_msg_display', 0);
    $is_front = drupal_is_front_page();

    if ($display == 0 || ($display == 1 && $is_front) || ($display == 2 && !$is_front)) {
      if (!variable_get('topbar_msg_context', 0)) {
        topbar_msg_display();
      }
      // @TODO verify context reaction name (topbar_msg_context_reaction_add?)
      else if ($plugin = context_get_plugin('reaction', 'topbar_msg_add')) {
        if ($plugin->execute()) {
          topbar_msg_display();
        }
      }
    }
  }
}

/**
 * Helper function to add Topbar Message to the page.
 */
function topbar_msg_display() {
  $module_path = drupal_get_path('module', 'topbar_msg');
  $settings = topbar_msg_get_settings();

  drupal_add_css($module_path . '/css/topbar_msg.css');
  drupal_add_js($module_path . '/js/topbar_msg.js');
  drupal_add_js(array('topbarMsg' => $settings), 'setting');
}

/**
 * Helper function to retrieve settings.
 */
function topbar_msg_get_settings() {
  $settings = array();

  $settings['message'] = variable_get('topbar_msg_message', 'No message added yet');
  $settings['link_text'] = variable_get('topbar_msg_link_text', 'Modify Settings');
  $settings['link'] = variable_get('topbar_msg_link', 'admin/config/system/topbar-message');
  $settings['link_target'] = variable_get('topbar_msg_new_window_link', TRUE) == TRUE ? '_blank' : '';
  $settings['autohide'] = variable_get('topbar_msg_autohide', FALSE);
  $settings['autohide_seconds'] = variable_get('topbar_msg_autohide_seconds', 5);
  $settings['cookie'] = variable_get('topbar_msg_cookie', FALSE);
  $settings['cookie_expire'] = variable_get('topbar_msg_cookie_expire', 1);
  $settings['color_bg'] = variable_get('topbar_msg_color_bg', '#000000');
  $settings['color_text'] = variable_get('topbar_msg_color_text', '#FFFFFF');
  $settings['color_link'] = variable_get('topbar_msg_color_link', '#FFFFFF');

  return $settings;
}
